### ISSUE TITLE
Pedigree Browser - goes back to signin screen on redirect

### ISSUE THREAD

**Issue by rjmarsh** [FamilySearch/fs-pedigree-browser-node#1]
Hi,

I'm new to FamilySearch development and am trying to get the Pedigree Browser sample to work on my machine. 

Problem:  After I login to the integration environment I get redirected back to the signin screen (rather than the pedigree).

Steps taken:

1) Created an app under my developer account (set Redirect URI to http://localhost:3000/oauth-redirect)
2) git clone https://github.com/FamilySearch/fs-pedigree-browser-node.git
3) cd fs-pedigree-browser-node
4) npm install
5) Updated  appKey in config/default.json to be the newly created App Key (from step 1)
6) Updated redirectURI in middleware/fs-client.js to the URI specified in step 1 above (domain + ':3000' + '/oauth-redirect')
7) npm run dev
8) Browse to localhost:3000 and login, enter integration environment credentials and submit
9) goes back to the signin screen

It appear that the following is happening:
1) oauth-redirect.js is storing the access token in req.session.fs_token then redirecting to /pedigree
2) the fs-session.js middleware intercepts the redirect to validate authentication and at this time req.session.fs_token does not have a value.
3) fs-session.js redirects to '/'

I don't know what I'm missing. Any guidance?

Thanks,

Russ

**Comment by justincy** [comment]
Sounds like a bug. Thanks for reporting. I'll take a look.

**Comment by justincy** [comment]
> It appear that the following is happening:
> 
> 1. oauth-redirect.js is storing the access token in req.session.fs_token then redirecting to /pedigree
> 2. the fs-session.js middleware intercepts the redirect to validate authentication and at this time req.session.fs_token does not have a value.
> 3. fs-session.js redirects to '/'

That's a good guess but that's not how it works. In `routes/oauth-redirect.js` we can see that the `fs-session.js` middleware isn't used on that route.

I'm having a hard time debugging because I'm unable to replicate the issue. @rjmarsh Can you help me a little more? The app logs all incoming requests. Logs will look like this:

```
GET /pedigree/KW3B-N7F 302 22.571 ms - 46
GET / 200 22.094 ms - 1196
GET /stylesheets/style.css 200 4.668 ms - 1419
GET /signin 302 2.812 ms - 458
GET /oauth-redirect?code=311012828-73-59-108-4527031-7432-117-4-94-88-67-112-8277911-95-1101098942-732642-45 302 349.664 ms - 62
```

Can you paste all log entries that are printed during the signin process?

**Comment by rjmarsh** [comment]
GET / 304 20.867 ms - -
GET /stylesheets/style.css 304 3.049 ms - -
GET /signin 302 8.187 ms - 392
GET /oauth-redirect?code=-23-35-6648-114-46491031241238-119-3853-43155312456564010068-11364337-94532780 302 358.594 ms - 62
GET /pedigree 302 0.873 ms - 46
GET / 304 2.332 ms - -
GET /stylesheets/style.css 304 0.928 ms - -

**Comment by justincy** [comment]
@rjmarsh I take back what I said earlier. You were right. I didn't understand properly what you were saying. I'm still trying to figure out why it's happening.

**Comment by rjmarsh** [comment]
oauth-redirect?code=-9589111111-62-20-42-410047-4812059-75543376-42-2929-99-111-10-48-7369-122-32847-112-35
------------------------------------------------------------------------------------------------------------
Request URL:http://localhost:3000/oauth-redirect?code=-9589111111-62-20-42-410047-4812059-75543376-42-2929-99-111-10-48-7369-122-32847-112-35
Request Method:GET
Status Code:302 Found
Remote Address:[::1]:3000
Response Headers
view source
Connection:keep-alive
Content-Length:62
Content-Type:text/html; charset=utf-8
Date:Fri, 03 Mar 2017 16:11:05 GMT
Location:/pedigree
Vary:Accept
X-Powered-By:Express
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:3000
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Query String Parameters
view source
view URL encoded
code:-9589111111-62-20-42-410047-4812059-75543376-42-2929-99-111-10-48-7369-122-32847-112-35

pedigree
-----------------------------------------------------------------
Request URL:http://localhost:3000/pedigree
Request Method:GET
Status Code:302 Found
Remote Address:[::1]:3000
Response Headers
view source
Connection:keep-alive
Content-Length:46
Content-Type:text/html; charset=utf-8
Date:Fri, 03 Mar 2017 16:11:05 GMT
Location:/
Vary:Accept
X-Powered-By:Express
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:3000
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

localhost
-------------------------------------------------------------------------------
Request URL:http://localhost:3000/
Request Method:GET
Status Code:304 Not Modified
Remote Address:[::1]:3000
Response Headers
view source
Connection:keep-alive
Date:Fri, 03 Mar 2017 16:11:05 GMT
ETag:W/"4cf-LJ6RebjVyu6NCxLUWKr7lA"
X-Powered-By:Express
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:3000
If-None-Match:W/"4cf-LJ6RebjVyu6NCxLUWKr7lA"
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by justincy** [comment]
Could you add the following line just before line 30 in `routes/oauth-redirect.js` and tell me what it prints out?

`console.log(tokenResponse);`

**Comment by rjmarsh** [comment]
[INFO] 09:18:45 Restarting
GET /signin 302 14.325 ms - 392
{ statusCode: 200,
  statusText: 'OK',
  headers:
   { server: 'Apache-Coyote/1.1',
     expires: 'Tue, 03 Jul 2001 06:00:00 GMT',
     'last-modified': 'Fri Mar 03 16:19:14 GMT 2017',
     'cache-control': 'no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0',
     pragma: 'no-cache',
     'content-type': 'application/json;charset=ISO-8859-1',
     'content-language': 'en-US',
     'content-length': '111',
     date: 'Fri, 03 Mar 2017 16:19:14 GMT',
     connection: 'close' },
  originalUrl: 'https://integration.familysearch.org/cis-web/oauth2/v3/token',
  effectiveUrl: 'https://integration.familysearch.org/cis-web/oauth2/v3/token',
  redirected: false,
  requestMethod: 'POST',
  requestHeaders: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: '{"access_token":"USYS70EDE83F12D61452157B60BB88A9A60D_idses-int01.a.fsglobal.net","token_type":"family_search"}',
  retries: 0,
  throttled: false,
  data:
   { access_token: 'USYS70EDE83F12D61452157B60BB88A9A60D_idses-int01.a.fsglobal.net',
     token_type: 'family_search' } }
GET /oauth-redirect?code=70-127-31-116-112113101-16126-3685102-22-127-76-71-99373142337618-123-46-4510888-11597105-80 302 333.628 ms - 62
GET /pedigree 302 1.368 ms - 46
GET / 304 17.138 ms - -
GET /stylesheets/style.css 304 2.331 ms - -

**Comment by justincy** [comment]
I think I figured it out. Try commenting out line 30 of `app.js`, If that doesn't work try setting `secure` to `false`.

**Comment by rjmarsh** [comment]
Beautiful!! It's working.

**Comment by justincy** [comment]
Thanks for working with me on that. I'll update the docs to discuss that setting in the setup instructions.

**Comment by misbach** [comment]
Should we default the cookie security to be false since most localhost sessions are not https?

**Comment by justincy** [comment]
@misbach Yeah that's a good idea.
